# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

CXXFLAGS  += -I.

# Optional Libraries -----------------------------------------------------

SDL       ?= 1

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
