# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
