# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

TEST_ARGS += 1

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
