# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

TEST_ARGS +=

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
