# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

CXXFLAGS += -DHAS_SIM_SETUP -I.

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
