# Sketch Makefile --------------------------------------------------------

BIN = $(shell basename `pwd`).exe

TIMEOUT   = 5
TEST_ARGS = 10

# Simduino Magic ---------------------------------------------------------

SIMDUINO  = ../../../Simduino
include $(SIMDUINO)/sketch.mk

# EOF --------------------------------------------------------------------
